### ISSUE TITLE
SVN serve doesn't start if svn_repository_home is set

### ISSUE THREAD

**Issue by memoryleak** [geerlingguy/ansible-role-svn#4]
System: CentOS Linux release 7.4.1708 (Core) 
Ansible version:  2.3.2.0

> systemd[1]: Starting Subversion protocol daemon...
> svnserve[29654]: svnserve: Root path '/var/svn' does not exist or is not a directory.
> systemd[1]: svnserve.service: control process exited, code=exited status=1
> systemd[1]: Failed to start Subversion protocol daemon.
> systemd[1]: Unit svnserve.service entered failed state.
> systemd[1]: svnserve.service failed.

```
- hosts: svn
  roles:
    - name: geerlingguy.svn
      svn_repository_home: /mnt/data/svn
      svn_create_test_repo: true

```
It seems that the /etc/sysconfig/svnserve still contains default /var/svn - thus svnserve not starting up.
