### ISSUE TITLE
Set SELinux context

### ISSUE THREAD

**Issue by m8ram** [geerlingguy/ansible-role-svn#7]
I added the following tasks to configure the SELinux context when using non default locations on RHEL:

```
- name: Allow apache to modify files in svn_repository_home
  sefcontext:
    target: "{{ svn_repository_home | regex_replace('\\/$', '') }}/[^/]*(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present
- name: Allow apache to modify SVN config files in svn_repository_home
  sefcontext:
    target: "{{ svn_repository_home | regex_replace('\\/$', '') }}/[^/]*/conf(/.*)?"
    setype: httpd_sys_content_t
    state: present
- name: Allow apache to modify SVN hooks in svn_repository_home
  sefcontext:
    target: "{{ svn_repository_home | regex_replace('\\/$', '') }}/[^/]*/hooks(/.*)?"
    setype: httpd_sys_script_exec_t
    state: present                                                
```

It requires an restorecon task as well after creating the repository
```
- name: Apply new SELinux file context to filesystem
  command: restorecon -irv "{{ svn_repository_home }}"
```
